### ISSUE TITLE
Copying output/errors

### ISSUE THREAD

**Issue by danuker** [allison-casey/hy-interpreter#2]
Hello!

Is this the interpreter running at https://hylang.github.io/hy-interpreter/ ? If not, I apologize, please close this.

I can't copy the error or output from the "Output" pane, in either Firefox 99.0.1 or Chromium 101.0.4951.41 on Arch Linux.

It would be very nice to be able to do so, since otherwise I can't search for error messages easily, and have to type them manually.

**Comment by Kodiologist** [comment]
This project has been replaced by https://github.com/hylang/hyhomepage.
